# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20160728_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Розвязок', 'verbose_name_plural': 'Розвязки'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексти'},
        ),
    ]
