# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExt',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField(max_length=255, verbose_name='Опис')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Зображення')),
            ],
            bases=('auth.group',),
        ),
    ]
