# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupext_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupext',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='groupext',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
