# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='token',
            field=models.CharField(default='t0ken', max_length=10),
        ),
    ]
