# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20160822_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupext',
            options={'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
