# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20160912_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupext',
            options={'permissions': (('group_user', 'Group user'),), 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
