# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20160912_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupext',
            options={'permissions': (('group_member', 'Group member'), ('group_admin', 'Group admin')), 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
